<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "admin_business".
 *
 * @property int $id
 * @property string $password 密码
 * @property string $username 用户名
 * @property int $bus_id
 * @property string $name 商户名称
 * @property string $auth_key
 * @property string $accessToken
 * @property string $phone 登录手机号
 */
class AdminBusiness extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'admin_business';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['bus_id', 'phone'], 'required'],
            [['bus_id'], 'integer'],
            [['password'], 'string', 'max' => 32],
            [['name'], 'string', 'max' => 30],
            [['auth_key', 'accessToken', 'phone'], 'string', 'max' => 50],
            ['username','unique'],
            ['username','string','min'=>6,'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'password' => '密码',
            'username' => '用户名',
            'bus_id' => '商户',
            'name' => '姓名',
            'auth_key' => 'Auth Key',
            'accessToken' => 'Access Token',
            'phone' => '登录手机号',
        ];
    }
    public function beforeSave($insert)
    {
        $dirtyAttributes=$this->getDirtyAttributes();
        if($insert || $dirtyAttributes['password']){
            $this->password=md5(md5("data.wedoctors").$this->password);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
