<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "goods".
 *
 * @property int $id
 * @property string $name 商品名称
 * @property string $goods_model 商品型号
 * @property string $make 品牌
 * @property string $car_model 适用车型
 * @property float $price 指导价格
 * @property string $remarks 备注
 * @property int $stock 库存
 * @property int $createtime 添加时间
 * @property int $updatetime 最新修改时间
 */
class Goods extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'goods';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['price'], 'number'],
            [['stock'], 'required'],
            [['stock'], 'integer'],
            [['createtime','updatetime'], 'string'],

            [['name', 'goods_model', 'make', 'car_model'], 'string', 'max' => 50],
            [['remarks'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '商品名称',
            'goods_model' => '商品型号',
            'make' => '品牌',
            'car_model' => '适用车型',
            'price' => '指导价格',
            'remarks' => '备注',
            'stock' => '库存',
            'category' => '分类',

            'createtime' => '添加时间',
            'updatetime' => '最新修改时间',
        ];
    }
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->createtime = date('Y-m-d H:i:s');
            $this->updatetime = date('Y-m-d H:i:s');

        }else{
            $this->updatetime = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
