<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string $orderid 订单号
 * @property string $customer 客户姓名
 * @property string $phone 电话
 * @property string $number 车牌号
 * @property string $vin 车架号
 * @property int $mileage 本次里程数
 * @property int $interval_mileage 间隔公里
 * @property string $car_model 车型
 * @property string $shop 店面
 * @property string $worker 维修工
 * @property int $createtime 添加时间
 * @property int $updatetime 修改时间
 */
class Orders extends \yii\db\ActiveRecord
{
    public static $interval_mileageText=[
        5000=>5000,
        7000=>7000,
        10000=>10000,
    ];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['customer', 'phone', 'number', 'vin', 'mileage', 'interval_mileage', 'car_model', 'shop', 'worker'], 'required'],
            [['mileage', 'interval_mileage'], 'integer'],
            [['orderid', 'customer', 'phone', 'vin', 'car_model', 'shop', 'worker'], 'string', 'max' => 50],
            [['createtime','updatetime'], 'string'],

            [['number'], 'string', 'max' => 20],
        ];
    }
    public function getGoods(){
        return $this->hasMany(OrdersGoods::className(), ['orderid' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'orderid' => '订单号',
            'customer' => '客户姓名',
            'phone' => '电话',
            'number' => '车牌号',
            'vin' => '车架号',
            'mileage' => '本次里程数',
            'interval_mileage' => '间隔公里',
            'car_model' => '车型',
            'shop' => '店面',
            'worker' => '维修工',
            'createtime' => '添加时间',
            'updatetime' => '修改时间',
        ];
    }
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->createtime = date('Y-m-d H:i:s');
            $this->updatetime = date('Y-m-d H:i:s');
            $this->orderid=date('YmdHis')+rand(0,1000);

        }else{
            $this->updatetime = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
