<?php

namespace platform\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $name 名称
 * @property int $bus_id 商户
 */
class Category extends \common\models\Category
{
    public function beforeSave($insert)
    {
        $this->bus_id=Yii::$app->user->identity->bus_id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
