<?php

namespace platform\models;

use Yii;

/**
 * This is the model class for table "goods".
 *
 * @property int $id
 * @property string $name 商品名称
 * @property string $goods_model 商品型号
 * @property string $make 品牌
 * @property string $car_model 适用车型
 * @property float $price 指导价格
 * @property string $remarks 备注
 * @property int $stock 库存
 * @property int $createtime 添加时间
 * @property int $updatetime 最新修改时间
 */
class Commodity extends \common\models\Commodity
{
    public function beforeSave($insert)
    {
        $this->bus_id=Yii::$app->user->identity->bus_id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
