<?php

namespace platform\models;

use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string $orderid 订单号
 * @property string $customer 客户姓名
 * @property string $phone 电话
 * @property string $number 车牌号
 * @property string $vin 车架号
 * @property int $mileage 本次里程数
 * @property int $interval_mileage 间隔公里
 * @property string $car_model 车型
 * @property string $shop 店面
 * @property string $worker 维修工
 * @property int $createtime 添加时间
 * @property int $updatetime 修改时间
 */
class Orders extends \common\models\Orders
{
   public function beforeSave($insert)
   {
       $this->bus_id=Yii::$app->user->identity->bus_id;
       return parent::beforeSave($insert); // TODO: Change the autogenerated stub
   }
}
